### ISSUE TITLE
CreateFromBlob crashing

### ISSUE THREAD

**Issue by FFRainman** [Azure/azure-sdk-for-media-services-extensions#40]
When loading a blob from an Uri and passing it into CreateFromBlob it crashes with the following (weird) error:

```
System.Data.Services.Client.DataServiceClientException
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code /><m:message xml:lang="en-US">AssetFile ContentFileSize must not be negative</m:message></m:error>
```

Example code:

```
MediaServicesCredentials _cachedCredentials = new MediaServicesCredentials(_mediaServicesAccountName, _mediaServicesAccountKey);

CloudMediaContext _context = new CloudMediaContext(_cachedCredentials);
            
CloudBlockBlob cloudBlockBlob = new CloudBlockBlob(new Uri(model.BlobUri));                

// This row crashes
IAsset inputAsset = _context.Assets.CreateFromBlob(cloudBlockBlob, storageAccount.Credentials, AssetCreationOptions.None);
```

If I take the same CloudBlockBlob and use a MemoryStream to create it, it works, example:
```
var assetName = Path.GetFileNameWithoutExtension(cloudBlockBlob.Name);

IAsset inputAsset = _context.Assets.Create(assetName, AssetCreationOptions.None);

var assetFile = inputAsset.AssetFiles.Create(cloudBlockBlob.Name);

using (var memoryStream = new MemoryStream())
{
        cloudBlockBlob.DownloadToStream(memoryStream);
        memoryStream.Position = 0;
        assetFile.Upload(memoryStream);
}
```

**Comment by mconverti** [comment]
@FFRainman The `CreateFromBlob` extension tries to set the `IAssetFile.ContentFileSize` and `IAssetFile.MimeType` properties after successfully creating the asset based on the `CloudBlockBlob.Properties` of your source blob instance (see [AssetBaseCollectionExtensions.cs#L522](https://github.com/Azure/azure-sdk-for-media-services-extensions/blob/cf32ab4435d49bdec42263f9b84d2892aeafcf90/MediaServices.Client.Extensions/AssetBaseCollectionExtensions.cs#L522)).

The problem is that `CloudBlockBlob.Properties` was not loaded after creating your source blob instance. Could you please try adding the following line of code before calling the `CreateFromBlob` extension?

```cs
cloudBlockBlob.FetchAttributes();
```

Hope it helps!
Mariano Converti
[http://southworks.com/blog/author/mconverti/](http://southworks.com/blog/author/mconverti/)

**Comment by FFRainman** [comment]
@mconverti Perfect, that solves my problem!

Hopefully this piece of information can help others as well. :)

**Comment by skymanaditya1** [comment]
@mconverti  I spent 2 hours trying to debug this on my own. I was using the CopyFromFile function and had to recently change it to CopyFromBlob but it was crashing with the exception similar to the one commented by @FFRainman . Hope this solution reaches its targeted audience.
